### ISSUE TITLE
fix typo: consult-dir-jump-file misnamed

### ISSUE THREAD

**Issue by localauthor** [karthink/consult-dir#1]
consult-dir-jump-file is misnamed here 😬

https://github.com/karthink/consult-dir/blob/a6e8a3c32687be1cebd1f3a436b4ffc445c57866/consult-dir.el#L252

(Excellent functionality in this package, by the way. Very pleased to have stumbled across it! (Also big fan of Popper ;)))

**Comment by karthink** [comment]
Well, dang. Thanks! Looks like I missed it because I didn't change the binding in my personal config when I renamed the function from *-file-jump to *-jump-file.

> Very pleased to have stumbled across it! 

consult-dir will be on MELPA soon. I was planning to publicize it a bit after that.
