### ISSUE TITLE
command to use to just enter the directory

### ISSUE THREAD

**Issue by anupam312nwd** [karthink/consult-dir#11]
Hi, I want to use `consult-dir` to just jump into a recent directory.
Which command should I be using for `consult-dir-default-command`?
I tried `(setq consult-dir-default-command #'return)` and `(setq consult-dir-default-command #'exit-minibuffer)` 
but both did not work.
Thanks for creating `consult-dir`.

**Comment by karthink** [comment]
This feature is now included in consult-dir (6ee8df75), see #15 for details.
