### ISSUE TITLE
Add a release tag

### ISSUE THREAD

**Issue by abcdw** [karthink/consult-dir#14]
Hi, add a tag please, 1.0 or something, so consult-dir can be easier added to different OS distributions. I plan to package it for GNU Guix.

**Comment by karthink** [comment]
@abcdw I added a v0.1 release. I'm not sure about the process, please let me know if it looks okay.

**Comment by abcdw** [comment]
@karthink Thank you!) I've sent a patch to guix-patches mailing list, it should be merged in a few next days, you can track its status here:  https://issues.guix.gnu.org/53813
