### ISSUE TITLE
consult-dir opens TRAMP connections for remote bookmarked locations

### ISSUE THREAD

**Issue by oantolin** [karthink/consult-dir#2]
It seem a little premature to connect to all remote locations when I may not even pick one of them.

**Comment by karthink** [comment]
Oops, thanks for catching that, should be fixed in 8ce630c6. Please test?

I was matching directories with file-directory-p, I'm guessing this is what caused TRAMP to connect. I switched to string-suffix-p "/", hopefully there are no edge cases with this.

**Comment by oantolin** [comment]
I used `string-suffix-p "/"` in my toy version of your `consult-dir` command for many months, so I can safely say that works just fine for both local & remote bookmarks. I'll test the commit and report back.

**Comment by oantolin** [comment]
Yep, works great with that change, thanks!
