### ISSUE TITLE
Can consult-dir fall back to find-file (so that it can use a user-entered directory)?

### ISSUE THREAD

**Issue by indigoviolet** [karthink/consult-dir#20]
I'd like to be able to explicitly find a directory if none of the source match the query I have.

**Comment by karthink** [comment]
This is possible but not implemented, as it's not clear at what point the command should (automatically) switch to `find-file`. Suppose it shouldn't be automatic, but triggered with a key instead. Then this is no different from simply calling `find-file` with `enable-recursive-minibuffers` turned on. 

If you use Embark, you could call `embark-become` and switch to `find-file` that way without losing what you've typed. This is what I've been doing.

**Comment by indigoviolet** [comment]
Ok, that makes sense. 

I realized that I have had a [discussion](https://github.com/minad/consult/issues/196) similar to this :)
