### ISSUE TITLE
feature suggestion: integration with zoxide

### ISSUE THREAD

**Issue by yherve** [karthink/consult-dir#29]
Hi. I have installed consult-dir yesterday and it is really awesome. It has already became my favourite way of opening files.

I have an idea of improvement (unfortunately I am a terrible lisp programmer, so I cannot do it myself)
I use zoxide all the time in the terminal as a replacement for 'cd'. zoxide remembers the directories and you can jump there quickly (there are other tools that do the same (like z and autojump)

It would be great if you add a category with zoxide remembered path. You can easily get them with:

``` bash
zoxide query -l
```

**Comment by karthink** [comment]
You can add a zoxide source for consult-dir in your config following the fasd example in [the wiki](https://github.com/karthink/consult-dir/wiki#directories-visited-in-the-shell-using-fasd), which does something very similar. You just have to change the names and replace the shell command being run from `fasd -ld` to `zoxide query -l`. Let me know if you need help with this.

**Comment by yherve** [comment]
It worked perfectly. Thanks and thanks again for this wonderful tool.  Here is the code adapted to zoxide:

``` lisp
(require 'consult-dir)
(defun consult-dir--zoxide-dirs ()
  "Return list of zoxide dirs."
  (split-string (shell-command-to-string "zoxide query -l") "\n" t))

;; A consult source that calls this function
(defvar consult-dir--source-zoxide
 `(:name     "zoxide"
   :narrow   ?z
   :category file
   :face     consult-file
   :history  file-name-history
   :enabled  ,(lambda () (executable-find "zoxide"))
   :items    ,#'consult-dir--zoxide-dirs)
  "zoxide directory source for `consult-dir'.")

;; Adding to the list of consult-dir sources
(add-to-list 'consult-dir-sources 'consult-dir--source-zoxide t)
```
