### ISSUE TITLE
Include Docker source example for Emacs 29?

### ISSUE THREAD

**Issue by edgar-vincent** [karthink/consult-dir#30]
Hi!

Thanks a lot for this excellent package. As you may know, the version of Tramp bundled with the forthcoming Emacs 29 release handles connections to Docker containers. The Docker source example in the README should thus probably be updated to include an example using `tramp-container`.

I use this extremely trivial function:
```elisp
(defun consult-dir--tramp-docker-hosts ()
  "Get a list of hosts from Docker."
  (when (require 'tramp-container nil t)
    (mapcar (lambda (e)
	    (concat "/docker:" (format "%s" (cadr e)) ":/"))
	  (tramp-docker--completion-function))))
```

Thanks a lot!

**Comment by karthink** [comment]
@edgar-vincent Thanks for reminding me about this.  I'll add it to consult-dir after Emacs 29 releases.

**Comment by nanounanue** [comment]
Thank you for your amazing work @karthink 

Waiting for this update! :)
