### ISSUE TITLE
Jump to current candidate's directory

### ISSUE THREAD

**Issue by sturgman** [karthink/consult-dir#37]
Thanks for the fantastic package. I wonder if it would be possible to provide an additional command (if the code already written can be adapted in this way).

Scenario: I am looking to edit a recent file so I do `(consult-recent-file)`. Upon looking at my list of candidates I realize that the file that I really want is not the recently visited one but another file in the same directory. If I do `(consult-dir)` at this point I can select to navigate to the recent directory but I'm still looking for recent files, which misses the file I want.

Request: Create a new command '(consult-dir-jump-to-path)' that looks at the current candidate to determine if it is a valid path/file and jumps to the path of the candidate to `(find-file)`

I am currently working around this by jumping to the file I don't want in my recentf list and then finding file again.

Thanks again for consult-dir! A truly great addition to vertico/consult/embark!

**Comment by sturgman** [comment]
Ah... I see that Issue #24 is similar to this. I'll take a look at the solutions there to see if I can hack something up.

**Comment by karthink** [comment]
> Request: Create a new command '(consult-dir-jump-to-path)' that looks at the current candidate to determine if it is a valid path/file and jumps to the path of the candidate to (find-file)

Can't you just use `embark-become`, `C-x C-f`?
