### ISSUE TITLE
Why not show git folders as projects?

### ISSUE THREAD

**Issue by alexei-28** [karthink/consult-dir#5]
Linux Mint 20.2

Emacs 27.2

Install package **consult** and **consult-dir**.

I go to my git project and use command :

`M-x consult-dir`

I want to show only project folder. So I press `p SPC`.

And here result:

![1](https://user-images.githubusercontent.com/303539/133921219-82e782ef-1202-42d3-b223-5ef7016f4058.png)

Questions:
1. Why not show my git project in `consult-dir` (In directory) ?
2. Is it possible to show **git** and **subversion** projects when press `p SPC` ?

**Comment by karthink** [comment]
1. consult-dir will show projects registered through Project.el or Projectile. Do you use either of the two?
2. Yes, assuming they are registered as projects using the above.

**Comment by alexei-28** [comment]
> 1. consult-dir will show projects registered through Project.el or Projectile. Do you use either of the two?
> 2. Yes, assuming they are registered as projects using the above.

1. Not. I'm not use either of the two.
2. Where I can find example to register my GIT/Subversion project by Project.el or Projectile?

**Comment by karthink** [comment]
Project.el support is built into Emacs. Running any project command in a git/svn directory will register the project. You can check out the `C-x p` keymap.

Alternatively, Projectile is available on MELPA. [The README](https://github.com/bbatsov/projectile) shows you how to use it.
