### ISSUE TITLE
consult-dir-jump-file - not work

### ISSUE THREAD

**Issue by alexei-28** [karthink/consult-dir#7]
Linux Mint 20
Emacs 27.1
packages: consult, consult-dir

I my folder Temp I want jump file myFile.txt

Steps:
![1](https://user-images.githubusercontent.com/303539/135745375-10f1845b-dcb6-48f2-9118-69a6ad558bae.png)
`M-x constult-dir-jump-file`
![2](https://user-images.githubusercontent.com/303539/135745383-4205d7f6-49e8-4321-af65-50eea660d4d9.png)
Here result:
![3](https://user-images.githubusercontent.com/303539/135745387-b9472fb6-f0b6-451e-9a15-e72160abb576.png)

What is this?

**Comment by karthink** [comment]
If you want to find a file somewhere inside a folder, you can use `consult-find`.

`consult-dir-jump-file` is for using from inside consult-dir, and you'll need to bind this to a key first.

Try the following:

1. Bind it to a key
```elisp
(define-key minibuffer-local-completion-map (kbd "C-x C-j") #'consult-dir-jump-file)
```

2. Call `consult-dir`, select the Temp folder.

3. type in some part of the file name you want, such as "my"

3. Press "C-x C-j" to call `consult-dir-jump-file`

Does that work?

**Comment by alexei-28** [comment]
> If you want to find a file somewhere inside a folder, you can use `consult-find`.
> 
> `consult-dir-jump-file` is for using from inside consult-dir, and you'll need to bind this to a key first.
> 
> Try the following:
> 
> 1. Bind it to a key
> 
> ```emacs-lisp
> (define-key minibuffer-local-completion-map (kbd "C-x C-j") #'consult-dir-jump-file)
> ```
> 
> 1. Call `consult-dir`, select the Temp folder.
> 2. type in some part of the file name you want, such as "my"
> 3. Press "C-x C-j" to call `consult-dir-jump-file`

Yes, now it's work. Thanks
